AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple web app saving forms to S3 
Parameters:
  FoodType:
    Type: String
    Default: Steak
    Description: Question to ask on the form
Resources:
  IndexFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: src/
      Environment:
        Variables:
          FOOD_TYPE: !Ref FoodType
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /
            Method: get

Outputs:
    ApiURL:
      Description: "API endpoint URL for Prod environment"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

